---
minecraft:
  hosts:
    master:
      ansible_host: IP
      ansible_user: root

  vars:
    getserver: https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar
    mc_path: /opt/minecraft
    yum:
      - java
      - vim
      - net-tools
      - tree
# MC Server Properties
    max_tick_time: 60000
    generator_settings:
    allow_nether: true
    force_gamemode: false
    gamemode: 0
    enable_query: false
    player_idle_timeout: 0
    difficulty: 1
    spawn_monsters: true
    op_permission_level: 4
    announce_player_achievements: true
    pvp: true
    snooper_enabled: true
    level_type: DEFAULT
    hardcore: false
    enable_command_block: false
    max_players: 20
    network_compression_threshold: 256
    resource_pack_sha1:
    max_world_size: 29999984
    server_port: 25565
    spawn_npcs: true
    allow_flight: false
    level_name: world
    view_distance: 10
    resource_pack:
    spawn_animals: true
    white_list: false
    generate_structures: true
    online_mode: true
    max_build_height: 256
    level_seed:
    prevent_proxy_connections: false
    motd: A Minecraft Server
    enable_rcon: false
