---
- name: "Create Minecraft Directory"
  file:
    path: "{{ mc_path }}"
    state: directory
    mode: 0770

- name: "Set Firewalld Port in CentOS"
  firewalld:
    zone: public
    port: "{{ server_port }}/tcp"
    state: enabled
  when: ansible_distribution == 'CentOS'
  ignore_errors: true

- name: "Install Java - CentOS"
  yum:
    name: java-21-openjdk.x86_64
    state: latest
  when: ansible_distribution == 'CentOS'

- name: "Set Firewall Port in Ubuntu"
  ufw:
    rule: allow
    port: "{{ server_port }}"
    proto: tcp
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: true

- name: "Install java - Ubuntu"
  apt:
    name: default-jre
    update_cache: true
    state: latest
  when: ansible_distribution == 'Ubuntu'
