---
- name: "Create Minecraft Directory"
  file:
    path: "{{ mc_path }}"
    state: directory
    mode: 0770

- name: "Set Firewalld Port in CentOS"
  firewalld:
    zone: public
    port: "{{ server_port }}/tcp"
    state: enabled
  when: ansible_distribution == 'CentOS'

- name: "Install CentOS Tools"
  yum:
    name: java
    state: latest
  when: ansible_distribution == 'CentOS'

- name: "Set Firewall Port in Ubuntu"
  ufw:
    rule: allow
    port: "{{ server_port }}"
    proto: tcp
  when: ansible_distribution == 'Ubuntu'

- name: "Install Ubuntu Tools"
  apt:
    name: default-jre
    update_cache: true
    state: latest
  when: ansible_distribution == 'Ubuntu'
